set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN T22 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property DONT_TOUCH true [get_cells -hierarchical -filter {NAME =~ *halka_osilator*}]
set_property ALLOW_COMBINATORIAL_LOOPS true [get_nets -hierarchical -filter {NAME =~ *halka_osilator*/chain*}]

set_false_path -from [get_cells -hierarchical -filter {NAME =~ *halka_osilator*/chain_reg*}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets -hierarchical -filter {NAME =~ *halka_osilator*/osc_out*}]

set_max_delay 2.000 -from [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_a_sync_reg[0]*}] -to [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_a_sync_reg[1]*}]
set_max_delay 2.000 -from [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_b_sync_reg[0]*}] -to [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_b_sync_reg[1]*}]

set_property LOC SLICE_X0Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[0].ro_inst*}]
set_property LOC SLICE_X0Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[1].ro_inst*}]
set_property LOC SLICE_X0Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[2].ro_inst*}]
set_property LOC SLICE_X0Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[3].ro_inst*}]
set_property LOC SLICE_X1Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[4].ro_inst*}]
set_property LOC SLICE_X1Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[5].ro_inst*}]
set_property LOC SLICE_X1Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[6].ro_inst*}]
set_property LOC SLICE_X1Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[7].ro_inst*}]
set_property LOC SLICE_X2Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[8].ro_inst*}]
set_property LOC SLICE_X2Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[9].ro_inst*}]
set_property LOC SLICE_X2Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[10].ro_inst*}]
set_property LOC SLICE_X2Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[11].ro_inst*}]
set_property LOC SLICE_X3Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[12].ro_inst*}]
set_property LOC SLICE_X3Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[13].ro_inst*}]
set_property LOC SLICE_X3Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[14].ro_inst*}]
set_property LOC SLICE_X3Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[15].ro_inst*}]
set_property LOC SLICE_X4Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[16].ro_inst*}]
set_property LOC SLICE_X4Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[17].ro_inst*}]
set_property LOC SLICE_X4Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[18].ro_inst*}]
set_property LOC SLICE_X4Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[19].ro_inst*}]
set_property LOC SLICE_X5Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[20].ro_inst*}]
set_property LOC SLICE_X5Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[21].ro_inst*}]
set_property LOC SLICE_X5Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[22].ro_inst*}]
set_property LOC SLICE_X5Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[23].ro_inst*}]
set_property LOC SLICE_X6Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[24].ro_inst*}]
set_property LOC SLICE_X6Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[25].ro_inst*}]
set_property LOC SLICE_X6Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[26].ro_inst*}]
set_property LOC SLICE_X6Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[27].ro_inst*}]
set_property LOC SLICE_X7Y0 [get_cells -hierarchical -filter {NAME =~ *gen_ro[28].ro_inst*}]
set_property LOC SLICE_X7Y1 [get_cells -hierarchical -filter {NAME =~ *gen_ro[29].ro_inst*}]
set_property LOC SLICE_X7Y2 [get_cells -hierarchical -filter {NAME =~ *gen_ro[30].ro_inst*}]
set_property LOC SLICE_X7Y3 [get_cells -hierarchical -filter {NAME =~ *gen_ro[31].ro_inst*}]

set_property ASYNC_REG true [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_a_sync_reg[*]}]
set_property ASYNC_REG true [get_cells -hierarchical -filter {NAME =~ *ro_puf_cekirdek*/ro_b_sync_reg[*]}]
